language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
install:
  - npm install
script:
  - npm run build
after_success:
  - npx travis-deploy-once "npx semantic-release"
