language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
install: npm install
jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test
    - stage: build
      node_js: '10'
      script:
        - npm run build
    - stage: release
      node_js: '10'
      skip_cleanup: true
      on:
        branch: release
      script: npx travis-deploy-once "npx semantic-release"
