language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '12'
  - '10'
  - '8'
install: npm install
jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test
    - stage: release
      node_js: '10'
      if: branch = master
      script: npx travis-deploy-once "npx semantic-release"
