language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
install: npm install
matrix:
  fast_finish: true
jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test
    - stage: build
      node_js: '10'
      script:
        - npm run build
    - stage: release
      node_js: '10'
      skip_cleanup: true
      on:
        branch: release
      script: npx semantic-release
